### PR TITLE
updated hero section

### PR DESCRIPTION
**Pull request by jc3lee**
It's not perfect but I've made the background cover the hero section. Translated the img down instead of position absolute for picture. And added a container div around to add a max width and center it on desktop

### CODE REVIEW

**Comment by jomefavourite** [comment]
Thanks for checking it, I'll merge and see what you did

**Comment by jomefavourite** [comment]
It looks much better now, I'll have to study you code and see how you did it. Thanks once again.

**Comment by jc3lee** [comment]
U're welcome 😄 ! Tell me if u want me to have another look later on.

**Comment by jomefavourite** [comment]
Yh, I will

**Pull request merged**
